export enum TypeSymbols {
  LOGGER = 'LOGGER',
  DB = 'DB',

  PROVIDER_REPOSITORY = 'PROVIDER_REPOSITORY',
  DEPLOYMENT_REPOSITORY = 'DEPLOYMENT_REPOSITORY',
  API_KEY_REPOSITORY = 'API_KEY_REPOSITORY',
  TENANT_REPOSITORY = 'TENANT_REPOSITORY',
  NEXT_AUTH_USER_REPOSITORY = 'NEXT_AUTH_USER_REPOSITORY',
  WEAVE_FLOW_REPOSITORY = 'WEAVE_FLOW_REPOSITORY',
  LLM_FLOW_REPOSITORY = 'LLM_FLOW_REPOSITORY',
}
