import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    { type: "doc", id: "intro", label: "Documentation" },
    { type: "doc", id: "quickstart", label: "Quickstart" },
    {
      type: "category",
      label: "Installation",
      items: [{ type: "autogenerated", dirName: "installation" }],
      collapsed: true,
    },
    {
      type: "category",
      label: "Usage",
      items: [{ type: "autogenerated", dirName: "usage" }],
      collapsed: true,
    },
    {
      type: "category",
      label: "Configuration",
      items: [
        {
          type: "autogenerated",
          dirName: "configuration",
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Troubleshooting",
      items: [
        {
          type: "autogenerated",
          dirName: "troubleshooting",
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Get Involved",
      items: [
        {
          type: "autogenerated",
          dirName: "get-involved",
        },
      ],
      collapsed: false,
    },
  ],
};

export default sidebars;
